trigger: none
pool: TodoPool

stages:
  - stage: initialization
    jobs:
      - job: 
        steps:
        - task: TerraformInstaller@1
          inputs:
           terraformVersion: 'latest'

        - task: TerraformTask@5
          displayName: Terraform Init
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Moule'
            backendServiceArm: 'Imdinfraconnect'
            backendAzureRmStorageAccountName: 'arshstg123'
            backendAzureRmContainerName: 'arshctrl123'
            backendAzureRmKey: 'terraform.tfvars'

        - task: TerraformTask@5
          displayName: Terraform Plan
          inputs:
             provider: 'azurerm'
             command: 'plan'
             environmentServiceNameAzureRM: 'Imdinfraconnect'

  - stage: Scanning
    jobs:
      - job: 
        displayName: Scan
        steps:
        


