trigger: none
pool: TodoPool

stages:
  - stage: initialization
    jobs:
      - job: 
        steps:
        - task: TerraformInstaller@1
          inputs:
           terraformVersion: 'latest'

        - task: TerraformTask@5
          displayName: Terraform Init
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Module'
            backendServiceArm: 'Imdinfraconnect'
            backendAzureRmStorageAccountName: 'arshstg123'
            backendAzureRmContainerName: 'arshctrl123'
            backendAzureRmKey: 'terraform.tfstate'

        - task: TerraformTask@5
          displayName: Terraform Plan
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Module'
            environmentServiceNameAzureRM: 'Imdinfraconnect'

  - stage: Scanning
    jobs:
      - job: 
        displayName: Scan
        steps:
        - task: tfsec@1
          inputs:
            version: 'v1.26.0'
            dir: '$(System.DefaultWorkingDirectory)/Module'


