trigger: none
pool: TodoPool

stages:
  - stage: Initialization
    jobs:
      - job: 
        steps:
        - task: TerraformInstaller@1
          inputs:
           terraformVersion: 'latest'

        - task: TerraformTask@5
          displayName: Terraform Init
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Module'
            backendServiceArm: 'Imdinfraconnect'
            backendAzureRmStorageAccountName: 'arshstg123'
            backendAzureRmContainerName: 'arshctrl123'
            backendAzureRmKey: 'terraform.tfstate'

        - task: TerraformTask@5
          displayName: Terraform Plan
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Module'
            environmentServiceNameAzureRM: 'Imdinfraconnect'

  - stage: Scanning
    jobs:
      - job: 
        displayName: Scan
        steps:
        - task: tfsec@1
          inputs:
            version: 'v1.26.0'
            dir: '$(System.DefaultWorkingDirectory)/Module'

  - stage: ManualApproval
    dependsOn: Initialization
    jobs:
      - job: 
        displayName: ManualApprove
        pool: server
        steps:
        - task: ManualValidation@1
          inputs:
            notifyUsers: 'imad3290@gmail.com'
            approvers: 'imad3290@gmail.com'

  - stage: Apply
    dependsOn: ManualApproval
    displayName: Apply
    jobs:
      - job:
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Module'
            backendServiceArm: 'Imdinfraconnect'
            backendAzureRmStorageAccountName: 'arshstg123'
            backendAzureRmContainerName: 'arshctrl123'
            backendAzureRmKey: 'terraform.tfstate'

        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Module'
            environmentServiceNameAzureRM: 'Imdinfraconnect'



